version: '3'

services:
  senzing-loader:
    environment:
      LC_CTYPE: en_US.utf8
      SENZING_ENGINE_CONFIGURATION_JSON: ${SENZING_ENGINE_CONFIGURATION_JSON}
      SENZING_RABBITMQ_HOST: rabbitmq
      SENZING_RABBITMQ_PASSWORD: bitnami
      SENZING_RABBITMQ_QUEUE: senzing
      SENZING_RABBITMQ_USERNAME: user
      SENZING_SUBCOMMAND: rabbitmq
      SENZING_THREADS_PER_PROCESS: 64
      SENZING_SKIP_DATABASE_PERFORMANCE_TEST: 1
    image: senzing/stream-loader:latest
    networks:
      - backend
    restart: on-failure

networks:
  backend:
