version: '3.2'
services:

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: bitnami/rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - backend
    restart: always

networks:
  backend:
