version: '3'

services:
  senzing-redoer:
    container_name: senzing-redoer
    environment:
      SENZING_ENGINE_CONFIGURATION_JSON: ${SENZING_ENGINE_CONFIGURATION_JSON}
      SENZING_SUBCOMMAND: redo
    image: senzing/redoer:latest
    container_name: senzing-redoer
    networks:
      - backend
    restart: on-failure

networks:
  backend:
