version: '3'
services:

  senzing-webapp:
    environment:
#     See https://github.com/Senzing/entity-search-web-app#configuration
      SENZING_API_SERVER_URL: ${SENZING_API_SERVER_URL:-http://senzing-rest-server:8250}
      SENZING_WEB_SERVER_ADMIN_AUTH_MODE: JWT
      SENZING_WEB_SERVER_PORT: 8251
    image: senzing/entity-search-web-app:${SENZING_DOCKER_IMAGE_VERSION_ENTITY_SEARCH_WEB_APP:-latest}
    networks:
      - backend
    ports:
      - 8251:8251
    restart: always

networks:
  backend:
