version: '3'

services:
  senzing-producer:
    container_name: senzing-producer
    environment:
      SENZING_DEFAULT_DATA_SOURCE: TEST
      SENZING_INPUT_URL: /loadtest-dataset-5K-with-datasource.json
      SENZING_RABBITMQ_EXCHANGE: senzing-rabbitmq-exchange
      SENZING_RABBITMQ_HOST: rabbitmq
      SENZING_RABBITMQ_PASSWORD: bitnami
      SENZING_RABBITMQ_QUEUE: senzing
      SENZING_RABBITMQ_USERNAME: user
      SENZING_SUBCOMMAND: json-to-rabbitmq
    image: senzing/stream-producer:latest
    networks:
      - backend
    read_only: true
    restart: on-failure
    volumes: 
      - ../data/loadtest-dataset-5K-with-datasource.json:/loadtest-dataset-5K-with-datasource.json

networks:
  backend:
